#开发环境配置
server:
  #端口
  port: 8087
  tomcat:
    uri-encoding: utf-8 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 登陆成功地址
    successUrl: /index
    password:
      maxRetryCount: 10
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/ry?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/laxy?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 初始化连接数大小
    initialSize: 5
    minIdle: 3
    # 最大连接数，设为0表示无限制。
    maxActive: 10
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.sbs
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    #configLocation: classpath:mybatis/mybatis-config.xml
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql  